// SPDX-FileCopyrightText: 2026 Thilina Lakshan <thilinalakshanmail@gmail.com>
// SPDX-License-Identifier: Apache-2.0

#include "app/KinemaApplication.h"
#include "config/AppSettings.h"
#include "ui/qml-bridge/MainController.h"

#include <QQmlApplicationEngine>
#include <QQmlExpression>
#include <QQuickStyle>
#include <QQuickWindow>
#include <QStandardPaths>
#include <QtTest>

#include <memory>

namespace {

bool isTargetWarning(const QString& message)
{
    return message.contains(QStringLiteral(
               "Created graphical object was not placed in the graphics scene"))
        || message.contains(QStringLiteral(
               "Detected anchors on an item that is managed by a layout"))
        || message.contains(QStringLiteral(
               "ReferenceError: subtitleSearchSheet is not defined"))
        || (message.contains(QStringLiteral("ToolBarPageHeader.qml"))
            && message.contains(QStringLiteral(
                "Unable to assign [undefined] to bool")))
        || (message.contains(QStringLiteral("PageRow.qml"))
            && message.contains(QStringLiteral(
                "Value is null and could not be converted to an object")));
}

QStringList& capturedWarnings()
{
    static QStringList messages;
    return messages;
}

QtMessageHandler& previousMessageHandler()
{
    static QtMessageHandler handler = nullptr;
    return handler;
}

void warningCollector(QtMsgType type, const QMessageLogContext& context,
    const QString& message)
{
    if (type == QtWarningMsg && isTargetWarning(message)) {
        capturedWarnings().append(message);
    }
    Q_UNUSED(context);
    Q_UNUSED(message);
}

class ScopedWarningCollector
{
public:
    ScopedWarningCollector()
    {
        capturedWarnings().clear();
        previousMessageHandler() = qInstallMessageHandler(warningCollector);
    }

    ~ScopedWarningCollector()
    {
        qInstallMessageHandler(previousMessageHandler());
        previousMessageHandler() = nullptr;
    }

    QStringList messages() const { return capturedWarnings(); }
};

void evaluate(QQmlApplicationEngine& engine, QObject* scope,
    const QString& source)
{
    QQmlExpression expression(engine.rootContext(), scope, source);
    const QVariant result = expression.evaluate();
    QVERIFY2(!expression.hasError(), qPrintable(expression.error().toString()));
    Q_UNUSED(result);
    QCoreApplication::processEvents(QEventLoop::AllEvents, 50);
}

} // namespace

// Auto-generated by qt_add_qml_module(dev.tlmtech.kinema.app).
Q_DECL_IMPORT void qml_register_types_dev_tlmtech_kinema_app();

class TestApplicationBoot : public QObject
{
    Q_OBJECT
private Q_SLOTS:
    void initTestCase();
    void loadsApplicationShell();
};

void TestApplicationBoot::initTestCase()
{
    QStandardPaths::setTestModeEnabled(true);
    QQuickStyle::setStyle(QStringLiteral("org.kde.desktop"));
    qml_register_types_dev_tlmtech_kinema_app();
}

void TestApplicationBoot::loadsApplicationShell()
{
    ScopedWarningCollector warningCollector;
    QQmlApplicationEngine engine;

    auto settings = std::make_unique<kinema::config::AppSettings>();
    kinema::ui::qml::MainController controller(*settings, engine);

    engine.loadFromModule(QStringLiteral("dev.tlmtech.kinema.app"),
        QStringLiteral("ApplicationShell"));

    QVERIFY2(!engine.rootObjects().isEmpty(),
        "ApplicationShell failed to load; check QML imports and QML_FILES.");
    auto* window = qobject_cast<QQuickWindow*>(engine.rootObjects().constFirst());
    QVERIFY2(window, "ApplicationShell root object is not a QQuickWindow.");
    QVERIFY2(window->property("pageStack").isValid(),
        "ApplicationShell root does not expose Kirigami.ApplicationWindow.pageStack.");

    evaluate(engine, window, QStringLiteral("showPage('search')"));
    evaluate(engine, window, QStringLiteral("showPage('browse')"));
    evaluate(engine, window, QStringLiteral("showPage('settings')"));
    evaluate(engine, window, QStringLiteral("showPage('discover')"));

    const auto warnings = warningCollector.messages();
    QVERIFY2(warnings.isEmpty(), qPrintable(warnings.join(QLatin1Char('\n'))));
}

int main(int argc, char** argv)
{
    if (qEnvironmentVariableIsEmpty("QT_QPA_PLATFORM")) {
        qputenv("QT_QPA_PLATFORM", "offscreen");
    }
    QStandardPaths::setTestModeEnabled(true);

    kinema::KinemaApplication app(argc, argv);
    app.configure();

    TestApplicationBoot tc;
    return QTest::qExec(&tc, argc, argv);
}

#include "tst_application_boot.moc"
