// SPDX-FileCopyrightText: 2026 Thilina Lakshan <thilinalakshanmail@gmail.com>
// SPDX-License-Identifier: Apache-2.0

#include "app/KinemaApplication.h"
#include "config/AppSettings.h"
#include "ui/qml-bridge/MainController.h"

#include <QQmlApplicationEngine>
#include <QQuickStyle>
#include <QQuickWindow>
#include <QStandardPaths>
#include <QtTest>

#include <memory>

// Auto-generated by qt_add_qml_module(dev.tlmtech.kinema.app).
Q_DECL_IMPORT void qml_register_types_dev_tlmtech_kinema_app();

class TestApplicationBoot : public QObject
{
    Q_OBJECT
private Q_SLOTS:
    void initTestCase();
    void loadsApplicationShell();
};

void TestApplicationBoot::initTestCase()
{
    QStandardPaths::setTestModeEnabled(true);
    QQuickStyle::setStyle(QStringLiteral("org.kde.desktop"));
    qml_register_types_dev_tlmtech_kinema_app();
}

void TestApplicationBoot::loadsApplicationShell()
{
    QQmlApplicationEngine engine;

    auto settings = std::make_unique<kinema::config::AppSettings>();
    kinema::ui::qml::MainController controller(*settings, engine);

    engine.loadFromModule(QStringLiteral("dev.tlmtech.kinema.app"),
        QStringLiteral("ApplicationShell"));

    QVERIFY2(!engine.rootObjects().isEmpty(),
        "ApplicationShell failed to load; check QML imports and QML_FILES.");
    auto* window = qobject_cast<QQuickWindow*>(engine.rootObjects().constFirst());
    QVERIFY2(window, "ApplicationShell root object is not a QQuickWindow.");
    QVERIFY2(window->property("pageStack").isValid(),
        "ApplicationShell root does not expose Kirigami.ApplicationWindow.pageStack.");
}

int main(int argc, char** argv)
{
    if (qEnvironmentVariableIsEmpty("QT_QPA_PLATFORM")) {
        qputenv("QT_QPA_PLATFORM", "offscreen");
    }
    QStandardPaths::setTestModeEnabled(true);

    kinema::KinemaApplication app(argc, argv);
    app.configure();

    TestApplicationBoot tc;
    return QTest::qExec(&tc, argc, argv);
}

#include "tst_application_boot.moc"
