// SPDX-FileCopyrightText: 2026 Thilina Lakshan <thilinalakshanmail@gmail.com>
// SPDX-License-Identifier: Apache-2.0

#include "app/KinemaApplication.h"
#include "ui/MainWindow.h"

#include <KAboutData>

#include <QCommandLineParser>

#ifdef KINEMA_HAVE_LIBMPV
#include <QQuickWindow>
#include <QSGRendererInterface>
#include <clocale>

// Auto-generated by `qt_add_qml_module` inside kinema_core; declared
// here so we can force-reference it below. Without this reference
// the linker discards the QML module's `QQmlModuleRegistration`
// static instance (kinema_core is a STATIC library), and the QML
// engine reports `<C++ type> is not a type` for every QML_ELEMENT
// in the player module.
Q_DECL_IMPORT void
qml_register_types_dev_tlmtech_kinema_player();
#endif

int main(int argc, char* argv[])
{
#ifdef KINEMA_HAVE_LIBMPV
    // libmpv's render API is OpenGL-only upstream; mpvqt enforces
    // this and logs a critical error if Qt Quick is configured for
    // any other RHI backend. Pin the API process-wide before any
    // QQuickWindow exists. Plasma 6 / Qt 6 default to OpenGL on
    // Linux already, so this is a belt-and-braces guard rather
    // than a behaviour change on the primary target platform.
    QQuickWindow::setGraphicsApi(QSGRendererInterface::OpenGL);

    // Force-link the QML module's auto-generated registration. Side
    // effect: the `QQmlModuleRegistration` static at the bottom of
    // the generated file constructs and registers every C++ type.
    // Calling the function itself is also a no-op safety net in case
    // the static didn't run for some other reason.
    qml_register_types_dev_tlmtech_kinema_player();
#endif

    kinema::KinemaApplication app(argc, argv);
    app.configure();

    // --help / --version, plus room for future CLI flags.
    QCommandLineParser parser;
    KAboutData::applicationData().setupCommandLine(&parser);
    parser.process(app);
    KAboutData::applicationData().processCommandLine(&parser);

#ifdef KINEMA_HAVE_LIBMPV
    // libmpv requires LC_NUMERIC to be "C" — otherwise its config
    // parser flips decimal separators in locales like de_DE and
    // mpv_create() aborts with "Non-C locale detected". QApplication
    // inherits the user's locale on construction, so we force
    // LC_NUMERIC back here, after QApplication has done its own
    // locale handling but before any MpvWidget is created. Only
    // LC_NUMERIC is touched, so Qt's locale-aware formatting and
    // the rest of the C library are unaffected.
    std::setlocale(LC_NUMERIC, "C");
#endif

    kinema::ui::MainWindow window(app.settings());
    window.show();

    return app.exec();
}
