// SPDX-FileCopyrightText: 2026 Thilina Lakshan <thilinalakshanmail@gmail.com>
// SPDX-License-Identifier: Apache-2.0

#include "app/KinemaApplication.h"
#include "ui/qml-bridge/MainController.h"

#include <KAboutData>

#include <QCommandLineParser>
#include <QQmlApplicationEngine>
#include <QQuickStyle>
#include <QQuickWindow>

#ifdef KINEMA_HAVE_LIBMPV
#include <QSGRendererInterface>
#include <clocale>
#endif

// Auto-generated by `qt_add_qml_module` for each module. Without
// these explicit references the linker discards the module's
// `QQmlModuleRegistration` static (kinema_core / kinema_qml_app
// are static libraries) and the QML engine reports `<C++ type>
// is not a type` for every `QML_ELEMENT` declared in the module.
Q_DECL_IMPORT void
qml_register_types_dev_tlmtech_kinema_app();
#ifdef KINEMA_HAVE_LIBMPV
Q_DECL_IMPORT void
qml_register_types_dev_tlmtech_kinema_player();
#endif

int main(int argc, char* argv[])
{
#ifdef KINEMA_HAVE_LIBMPV
    // libmpv's render API is OpenGL-only upstream; mpvqt enforces
    // this and logs a critical error if Qt Quick is configured for
    // any other RHI backend. Pin the API process-wide before any
    // QQuickWindow exists.
    QQuickWindow::setGraphicsApi(QSGRendererInterface::OpenGL);
#endif

    // qqc2-desktop-style → Breeze for stock QQC2 controls inside
    // Kirigami pages. Soft runtime dep — falls back to `Default`
    // style when missing. Must run before any QQuickWindow /
    // QQmlEngine is constructed.
    QQuickStyle::setStyle(QStringLiteral("org.kde.desktop"));

    qml_register_types_dev_tlmtech_kinema_app();
#ifdef KINEMA_HAVE_LIBMPV
    qml_register_types_dev_tlmtech_kinema_player();
#endif

    kinema::KinemaApplication app(argc, argv);
    app.configure();

    QCommandLineParser parser;
    KAboutData::applicationData().setupCommandLine(&parser);
    parser.process(app);
    KAboutData::applicationData().processCommandLine(&parser);

#ifdef KINEMA_HAVE_LIBMPV
    // libmpv requires LC_NUMERIC to be "C" — otherwise its config
    // parser flips decimal separators in locales like de_DE and
    // mpv_create() aborts with "Non-C locale detected".
    // QApplication inherits the user's locale on construction, so
    // we force LC_NUMERIC back here, after QApplication has done
    // its own locale handling but before any MpvVideoItem is
    // created. Only LC_NUMERIC is touched.
    std::setlocale(LC_NUMERIC, "C");
#endif

    QQmlApplicationEngine engine;

    // Owns every long-lived service the app needs (HTTP, DB,
    // tokens, history, subtitles, tray, embedded playback) and
    // registers the `image://kinema/...` provider plus the
    // `mainController` context property on the engine. Phase 02
    // takes over composition entirely from the deleted
    // `MainWindow`; phases 03+ add per-page view-models alongside.
    kinema::ui::qml::MainController controller(
        app.settings(), engine, &app);

    engine.loadFromModule(QStringLiteral("dev.tlmtech.kinema.app"),
        QStringLiteral("ApplicationShell"));
    if (engine.rootObjects().isEmpty()) {
        return 1;
    }

    auto* window
        = qobject_cast<QQuickWindow*>(engine.rootObjects().first());
    Q_ASSERT(window);
    // Hand the live window over so the controller can wire the
    // tray, embedded-player transient parenting, and the close
    // handler against it.
    controller.attachWindow(window);

    return app.exec();
}
