// SPDX-FileCopyrightText: 2026 Thilina Lakshan <thilinalakshanmail@gmail.com>
// SPDX-License-Identifier: Apache-2.0

#include "app/KinemaApplication.h"
#include "ui/MainWindow.h"
#include "ui/qml-bridge/MainController.h"

#include <KAboutData>

#include <QCommandLineParser>
#include <QQmlApplicationEngine>
#include <QQuickStyle>

#ifdef KINEMA_HAVE_LIBMPV
#include <QQuickWindow>
#include <QSGRendererInterface>
#include <clocale>
#endif

// Auto-generated by `qt_add_qml_module` inside `kinema_core`. The
// app shell module is always built, so we always force-link it;
// the player module is gated on libmpv. Without these references
// the linker discards the modules' `QQmlModuleRegistration` static
// instances (kinema_core is a STATIC library), and the QML engine
// reports `<C++ type> is not a type` for every `QML_ELEMENT`
// declared in the module.
Q_DECL_IMPORT void
qml_register_types_dev_tlmtech_kinema_app();
#ifdef KINEMA_HAVE_LIBMPV
Q_DECL_IMPORT void
qml_register_types_dev_tlmtech_kinema_player();
#endif

int main(int argc, char* argv[])
{
#ifdef KINEMA_HAVE_LIBMPV
    // libmpv's render API is OpenGL-only upstream; mpvqt enforces
    // this and logs a critical error if Qt Quick is configured for
    // any other RHI backend. Pin the API process-wide before any
    // QQuickWindow exists. Plasma 6 / Qt 6 default to OpenGL on
    // Linux already, so this is a belt-and-braces guard rather
    // than a behaviour change on the primary target platform.
    QQuickWindow::setGraphicsApi(QSGRendererInterface::OpenGL);
#endif

    // Pin the Qt Quick Controls 2 style to KDE's `org.kde.desktop`
    // (qqc2-desktop-style). Without this, stock QQC2 controls
    // inside Kirigami pages fall back to the `Default` style and
    // visibly clash with the Breeze chrome around them. Phase 01
    // moves this out of the libmpv-only block: the app shell is
    // QtQuick / Kirigami unconditionally now, so the style
    // selection has to happen for every build.
    // Must run before any QQuickWindow / QQmlEngine is constructed.
    // If qqc2-desktop-style isn't installed the engine silently
    // falls back to `Default` — soft runtime dependency, no fatal.
    QQuickStyle::setStyle(QStringLiteral("org.kde.desktop"));

    // Force-link both QML modules' auto-generated registration.
    // Side effect: each `QQmlModuleRegistration` static at the
    // bottom of the generated file constructs and registers every
    // C++ type. Calling the function itself is also a no-op safety
    // net in case the static didn't run for some other reason.
    qml_register_types_dev_tlmtech_kinema_app();
#ifdef KINEMA_HAVE_LIBMPV
    qml_register_types_dev_tlmtech_kinema_player();
#endif

    kinema::KinemaApplication app(argc, argv);
    app.configure();

    // --help / --version, plus room for future CLI flags.
    QCommandLineParser parser;
    KAboutData::applicationData().setupCommandLine(&parser);
    parser.process(app);
    KAboutData::applicationData().processCommandLine(&parser);

#ifdef KINEMA_HAVE_LIBMPV
    // libmpv requires LC_NUMERIC to be "C" — otherwise its config
    // parser flips decimal separators in locales like de_DE and
    // mpv_create() aborts with "Non-C locale detected". QApplication
    // inherits the user's locale on construction, so we force
    // LC_NUMERIC back here, after QApplication has done its own
    // locale handling but before any MpvWidget is created. Only
    // LC_NUMERIC is touched, so Qt's locale-aware formatting and
    // the rest of the C library are unaffected.
    std::setlocale(LC_NUMERIC, "C");
#endif

    QQmlApplicationEngine engine;

    // MainController owns the engine-side image provider and
    // `mainController` context property. Phase 02+ grows it into
    // the canonical owner of every controller / view-model that
    // currently lives inside `MainWindow`.
    kinema::ui::qml::MainController controller(
        app.settings(), engine, &app);

    engine.loadFromModule(QStringLiteral("dev.tlmtech.kinema.app"),
        QStringLiteral("ApplicationShell"));
    if (engine.rootObjects().isEmpty()) {
        return 1;
    }

    // Legacy widget shell, kept hidden in phase 01 so the existing
    // search / detail / streams / settings / tray / embedded-player
    // surfaces keep working while the QML shell only carries
    // placeholder pages. Phase 02 rewires the embedded player's
    // transient parent onto the QML window and deletes this shim.
    kinema::ui::MainWindow legacyShell(app.settings());
    legacyShell.hide();

    return app.exec();
}
